// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_order_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_UserOrderInfo _$UserOrderInfoFromJson(Map<String, dynamic> json) =>
    _UserOrderInfo(
      adzoneName: json['adzoneName'] as String? ?? '',
      adzoneid: json['adzoneid'] as String? ?? '',
      alimamaRate: json['alimamaRate'] as String? ?? '',
      alimamaShareFee: json['alimamaShareFee'] as String? ?? '',
      alipayTotalPrice: json['alipayTotalPrice'] as String? ?? '',
      clickTime: json['clickTime'] as String? ?? '',
      depositPrice: json['depositPrice'] as String? ?? '',
      flowSource: json['flowSource'] as String? ?? '',
      id: (json['id'] as num?)?.toInt() ?? 0,
      incomeRate: json['incomeRate'] as String? ?? '',
      itemCategoryName: json['itemCategoryName'] as String? ?? '',
      itemImg: json['itemImg'] as String? ?? '',
      itemLink: json['itemLink'] as String? ?? '',
      itemNum: (json['itemNum'] as num?)?.toInt() ?? 0,
      itemPrice: json['itemPrice'] as String? ?? '',
      itemTitle: json['itemTitle'] as String? ?? '',
      itemid: json['itemid'] as String? ?? '',
      orderType: json['orderType'] as String? ?? '',
      pubShareFee: json['pubShareFee'] as String? ?? '',
      pubSharePreFee: json['pubSharePreFee'] as String? ?? '',
      pubShareRate: json['pubShareRate'] as String? ?? '',
      pubid: (json['pubid'] as num?)?.toInt() ?? 0,
      refundTag: (json['refundTag'] as num?)?.toInt() ?? 0,
      relationId:
          json['relationId'] == null ? '' : _toString(json['relationId']),
      sellerNick: json['sellerNick'] as String? ?? '',
      sellerShopTitle: json['sellerShopTitle'] as String? ?? '',
      siteName: json['siteName'] as String? ?? '',
      siteid: (json['siteid'] as num?)?.toInt() ?? 0,
      subsidyFee: json['subsidyFee'] as String? ?? '',
      subsidyRate: json['subsidyRate'] as String? ?? '',
      subsidyType: json['subsidyType'] as String? ?? '',
      tbDepositTime: json['tbDepositTime'] as String? ?? '',
      tbPaidTime: json['tbPaidTime'] as String? ?? '',
      terminalType: json['terminalType'] as String? ?? '',
      tkCommissionFeeForMediaPlatform:
          json['tkCommissionFeeForMediaPlatform'] as String? ?? '',
      tkCommissionPreFeeForMediaPlatform:
          json['tkCommissionPreFeeForMediaPlatform'] as String? ?? '',
      tkCommissionRateForMediaPlatform:
          json['tkCommissionRateForMediaPlatform'] as String? ?? '',
      tkCreateTime: json['tkCreateTime'] as String? ?? '',
      tkDepositTime: json['tkDepositTime'] as String? ?? '',
      tkOrderRole: (json['tkOrderRole'] as num?)?.toInt() ?? 0,
      tkPaidTime: json['tkPaidTime'] as String? ?? '',
      tkStatus: (json['tkStatus'] as num?)?.toInt() ?? 0,
      tkTotalRate: json['tkTotalRate'] as String? ?? '',
      totalCommissionFee: json['totalCommissionFee'] as String? ?? '',
      totalCommissionRate: json['totalCommissionRate'] as String? ?? '',
      tradeParentid: json['tradeParentid'] as String? ?? '',
      tradeid: json['tradeid'] as String? ?? '',
      zheAccount: json['zheAccount'] as String? ?? '',
      zheActId: json['zheActId'] as String? ?? '',
      zheAppKey: json['zheAppKey'] as String? ?? '',
      zheCode: json['zheCode'] as String? ?? '',
      zheCustomerIdZtk: json['zheCustomerIdZtk'] as String? ?? '',
      zheIsJieSuan: json['zheIsJieSuan'] as String? ?? '',
      zheJieSuanProfit: json['zheJieSuanProfit'] as String? ?? '',
      zheJieSuanTime: json['zheJieSuanTime'] as String? ?? '',
      zheOrderId: json['zheOrderId'] as String? ?? '',
      zhePayPrice: json['zhePayPrice'] as String? ?? '',
      zhePayTime: json['zhePayTime'] as String? ?? '',
      zhePlatformZtk: json['zhePlatformZtk'] as String? ?? '',
      zheProfit: json['zheProfit'] as String? ?? '',
      zheRefundPrice: json['zheRefundPrice'] as String? ?? '',
      zheRefundTime: json['zheRefundTime'] as String? ?? '',
      zheSanPingTai: json['zheSanPingTai'] as String? ?? '',
      zheSanPingTaiId: json['zheSanPingTaiId'] as String? ?? '',
      zheSid: json['zheSid'] as String? ?? '',
      zheSidZtk: json['zheSidZtk'] as String? ?? '',
      zheSmsTitle: json['zheSmsTitle'] as String? ?? '',
      zheStatus: json['zheStatus'] as String? ?? '',
      zheType: json['zheType'] as String? ?? '',
      zheUpdateTime: json['zheUpdateTime'] as String? ?? '',
    );

Map<String, dynamic> _$UserOrderInfoToJson(_UserOrderInfo instance) =>
    <String, dynamic>{
      'adzoneName': instance.adzoneName,
      'adzoneid': instance.adzoneid,
      'alimamaRate': instance.alimamaRate,
      'alimamaShareFee': instance.alimamaShareFee,
      'alipayTotalPrice': instance.alipayTotalPrice,
      'clickTime': instance.clickTime,
      'depositPrice': instance.depositPrice,
      'flowSource': instance.flowSource,
      'id': instance.id,
      'incomeRate': instance.incomeRate,
      'itemCategoryName': instance.itemCategoryName,
      'itemImg': instance.itemImg,
      'itemLink': instance.itemLink,
      'itemNum': instance.itemNum,
      'itemPrice': instance.itemPrice,
      'itemTitle': instance.itemTitle,
      'itemid': instance.itemid,
      'orderType': instance.orderType,
      'pubShareFee': instance.pubShareFee,
      'pubSharePreFee': instance.pubSharePreFee,
      'pubShareRate': instance.pubShareRate,
      'pubid': instance.pubid,
      'refundTag': instance.refundTag,
      'relationId': instance.relationId,
      'sellerNick': instance.sellerNick,
      'sellerShopTitle': instance.sellerShopTitle,
      'siteName': instance.siteName,
      'siteid': instance.siteid,
      'subsidyFee': instance.subsidyFee,
      'subsidyRate': instance.subsidyRate,
      'subsidyType': instance.subsidyType,
      'tbDepositTime': instance.tbDepositTime,
      'tbPaidTime': instance.tbPaidTime,
      'terminalType': instance.terminalType,
      'tkCommissionFeeForMediaPlatform':
          instance.tkCommissionFeeForMediaPlatform,
      'tkCommissionPreFeeForMediaPlatform':
          instance.tkCommissionPreFeeForMediaPlatform,
      'tkCommissionRateForMediaPlatform':
          instance.tkCommissionRateForMediaPlatform,
      'tkCreateTime': instance.tkCreateTime,
      'tkDepositTime': instance.tkDepositTime,
      'tkOrderRole': instance.tkOrderRole,
      'tkPaidTime': instance.tkPaidTime,
      'tkStatus': instance.tkStatus,
      'tkTotalRate': instance.tkTotalRate,
      'totalCommissionFee': instance.totalCommissionFee,
      'totalCommissionRate': instance.totalCommissionRate,
      'tradeParentid': instance.tradeParentid,
      'tradeid': instance.tradeid,
      'zheAccount': instance.zheAccount,
      'zheActId': instance.zheActId,
      'zheAppKey': instance.zheAppKey,
      'zheCode': instance.zheCode,
      'zheCustomerIdZtk': instance.zheCustomerIdZtk,
      'zheIsJieSuan': instance.zheIsJieSuan,
      'zheJieSuanProfit': instance.zheJieSuanProfit,
      'zheJieSuanTime': instance.zheJieSuanTime,
      'zheOrderId': instance.zheOrderId,
      'zhePayPrice': instance.zhePayPrice,
      'zhePayTime': instance.zhePayTime,
      'zhePlatformZtk': instance.zhePlatformZtk,
      'zheProfit': instance.zheProfit,
      'zheRefundPrice': instance.zheRefundPrice,
      'zheRefundTime': instance.zheRefundTime,
      'zheSanPingTai': instance.zheSanPingTai,
      'zheSanPingTaiId': instance.zheSanPingTaiId,
      'zheSid': instance.zheSid,
      'zheSidZtk': instance.zheSidZtk,
      'zheSmsTitle': instance.zheSmsTitle,
      'zheStatus': instance.zheStatus,
      'zheType': instance.zheType,
      'zheUpdateTime': instance.zheUpdateTime,
    };
