// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'zhe_product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_ZheProduct _$ZheProductFromJson(Map<String, dynamic> json) => _ZheProduct(
  code: json['code'] as String? ?? '',
  typeOneId: json['type_one_id'] as String? ?? '',
  taoId: json['tao_id'] as String? ?? '',
  title: json['title'] as String? ?? '',
  jianjie: json['jianjie'] as String? ?? '',
  pictUrl: json['pict_url'] as String? ?? '',
  userType: json['user_type'] as String? ?? '',
  sellerId: json['seller_id'] as String? ?? '',
  shopDsr: json['shop_dsr'] as String? ?? '',
  volume: json['volume'] as String? ?? '',
  size: json['size'] as String? ?? '',
  quanhouJiage: json['quanhou_jiage'] as String? ?? '',
  dateTimeYongjin: json['date_time_yongjin'] as String? ?? '',
  tkrate3: json['tkrate3'] as String? ?? '',
  yongjinType: json['yongjin_type'] as String? ?? '',
  couponId: json['coupon_id'] as String? ?? '',
  couponStartTime: json['coupon_start_time'] as String? ?? '',
  couponEndTime: json['coupon_end_time'] as String? ?? '',
  couponInfoMoney: json['coupon_info_money'] as String? ?? '',
  couponTotalCount: json['coupon_total_count'] as String? ?? '',
  couponRemainCount: json['coupon_remain_count'] as String? ?? '',
  couponInfo: json['coupon_info'] as String? ?? '',
  juhuasuan: json['juhuasuan'] as String? ?? '',
  taoqianggou: json['taoqianggou'] as String? ?? '',
  haitao: json['haitao'] as String? ?? '',
  jiyoujia: json['jiyoujia'] as String? ?? '',
  jinpaimaijia: json['jinpaimaijia'] as String? ?? '',
  pinpai: json['pinpai'] as String? ?? '',
  pinpaiName: json['pinpai_name'] as String? ?? '',
  yunfeixian: json['yunfeixian'] as String? ?? '',
  nick: json['nick'] as String? ?? '',
  smallImages: json['small_images'] as String? ?? '',
  whiteImage: json['white_image'] as String? ?? '',
  taoTitle: json['tao_title'] as String? ?? '',
  provcity: json['provcity'] as String? ?? '',
  shopTitle: json['shop_title'] as String? ?? '',
  zhiboUrl: json['zhibo_url'] as String? ?? '',
  sellCount: json['sellCount'] as String? ?? '',
  commentCount: json['commentCount'] as String? ?? '',
  favcount: json['favcount'] as String? ?? '',
  score1: json['score1'] as String? ?? '',
  score2: json['score2'] as String? ?? '',
  score3: json['score3'] as String? ?? '',
  creditLevel: json['creditLevel'] as String? ?? '',
  shopIcon: json['shopIcon'] as String? ?? '',
  pcDescContent: json['pcDescContent'] as String? ?? '',
  itemUrl: json['item_url'] as String? ?? '',
  categoryId: json['category_id'] as String? ?? '',
  categoryName: json['category_name'] as String? ?? '',
  levelOneCategoryId: json['level_one_category_id'] as String? ?? '',
  levelOneCategoryName: json['level_one_category_name'] as String? ?? '',
  tkfee3: json['tkfee3'] as String? ?? '',
  biaoqian: json['biaoqian'] as String? ?? '',
  tag: json['tag'] as String? ?? '',
  dateTime: json['date_time'] as String? ?? '',
  presaleDiscountFeeText: json['presale_discount_fee_text'] as String? ?? '',
  presaleTailEndTime: json['presale_tail_end_time'] as String? ?? '',
  presaleTailStartTime: json['presale_tail_start_time'] as String? ?? '',
  presaleEndTime: json['presale_end_time'] as String? ?? '',
  presaleStartTime: json['presale_start_time'] as String? ?? '',
  presaleDeposit: json['presale_deposit'] as String? ?? '',
);

Map<String, dynamic> _$ZheProductToJson(_ZheProduct instance) =>
    <String, dynamic>{
      'code': instance.code,
      'type_one_id': instance.typeOneId,
      'tao_id': instance.taoId,
      'title': instance.title,
      'jianjie': instance.jianjie,
      'pict_url': instance.pictUrl,
      'user_type': instance.userType,
      'seller_id': instance.sellerId,
      'shop_dsr': instance.shopDsr,
      'volume': instance.volume,
      'size': instance.size,
      'quanhou_jiage': instance.quanhouJiage,
      'date_time_yongjin': instance.dateTimeYongjin,
      'tkrate3': instance.tkrate3,
      'yongjin_type': instance.yongjinType,
      'coupon_id': instance.couponId,
      'coupon_start_time': instance.couponStartTime,
      'coupon_end_time': instance.couponEndTime,
      'coupon_info_money': instance.couponInfoMoney,
      'coupon_total_count': instance.couponTotalCount,
      'coupon_remain_count': instance.couponRemainCount,
      'coupon_info': instance.couponInfo,
      'juhuasuan': instance.juhuasuan,
      'taoqianggou': instance.taoqianggou,
      'haitao': instance.haitao,
      'jiyoujia': instance.jiyoujia,
      'jinpaimaijia': instance.jinpaimaijia,
      'pinpai': instance.pinpai,
      'pinpai_name': instance.pinpaiName,
      'yunfeixian': instance.yunfeixian,
      'nick': instance.nick,
      'small_images': instance.smallImages,
      'white_image': instance.whiteImage,
      'tao_title': instance.taoTitle,
      'provcity': instance.provcity,
      'shop_title': instance.shopTitle,
      'zhibo_url': instance.zhiboUrl,
      'sellCount': instance.sellCount,
      'commentCount': instance.commentCount,
      'favcount': instance.favcount,
      'score1': instance.score1,
      'score2': instance.score2,
      'score3': instance.score3,
      'creditLevel': instance.creditLevel,
      'shopIcon': instance.shopIcon,
      'pcDescContent': instance.pcDescContent,
      'item_url': instance.itemUrl,
      'category_id': instance.categoryId,
      'category_name': instance.categoryName,
      'level_one_category_id': instance.levelOneCategoryId,
      'level_one_category_name': instance.levelOneCategoryName,
      'tkfee3': instance.tkfee3,
      'biaoqian': instance.biaoqian,
      'tag': instance.tag,
      'date_time': instance.dateTime,
      'presale_discount_fee_text': instance.presaleDiscountFeeText,
      'presale_tail_end_time': instance.presaleTailEndTime,
      'presale_tail_start_time': instance.presaleTailStartTime,
      'presale_end_time': instance.presaleEndTime,
      'presale_start_time': instance.presaleStartTime,
      'presale_deposit': instance.presaleDeposit,
    };
