// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Product _$ProductFromJson(Map<String, dynamic> json) => _Product(
  teamName: json['teamName'] as String? ?? '',
  tbcid: json['tbcid'] as num? ?? 0,
  shipPercent: json['shipPercent'] as num? ?? 0,
  itemLink: json['itemLink'] as String? ?? '',
  freeshipRemoteDistrict: json['freeshipRemoteDistrict'] as num? ?? 0,
  yunfeixian: json['yunfeixian'] as num? ?? 0,
  goldSellers: json['goldSellers'] as num? ?? 0,
  reimgs: json['reimgs'] as String? ?? '',
  couponLink: json['couponLink'] as String? ?? '',
  haitao: json['haitao'] as num? ?? 0,
  sellerId: json['sellerId'] as String? ?? '',
  discounts: json['discounts'] as num? ?? 0,
  directCommissionLink: json['directCommissionLink'] as String? ?? '',
  couponStartTime: json['couponStartTime'] as String? ?? '',
  serviceScore: json['serviceScore'] as num? ?? 0,
  mainPic: json['mainPic'] as String? ?? '',
  id: json['id'] as num? ?? 0,
  brand: json['brand'] as num? ?? 0,
  imgs: json['imgs'] as String? ?? '',
  brandName: json['brandName'] as String? ?? '',
  couponConditions: json['couponConditions'] as String? ?? '',
  detailPics: json['detailPics'] as String? ?? '',
  subcid: json['subcid'] as List<dynamic>? ?? const [],
  subdivisionId: json['subdivisionId'] as num? ?? 0,
  dsrScore: json['dsrScore'] as num? ?? 0,
  dailySales: json['dailySales'] as num? ?? 0,
  shopLogo: json['shopLogo'] as String? ?? '',
  shopLevel: json['shopLevel'] as num? ?? 0,
  couponTotalNum: json['couponTotalNum'] as num? ?? 0,
  descScore: json['descScore'] as num? ?? 0,
  brandWenan: json['brandWenan'] as String? ?? '',
  activityEndTime: json['activityEndTime'] as String? ?? '',
  shipScore: json['shipScore'] as num? ?? 0,
  brandId: json['brandId'],
  couponReceiveNum: json['couponReceiveNum'] as num? ?? 0,
  shopType: json['shopType'] as num? ?? 0,
  cid: json['cid'] as num? ?? 0,
  desc: json['desc'] as String? ?? '',
  commissionRate: json['commissionRate'] as num? ?? 0,
  originalPrice: json['originalPrice'] as num? ?? 0,
  actualPrice: json['actualPrice'] as num? ?? 0,
  goodsId: json['goodsId'] as String? ?? '',
  quanMLink: json['quanMLink'] as num? ?? 0,
  shopName: json['shopName'] as String? ?? '',
  activityStartTime: json['activityStartTime'] as String? ?? '',
  video: json['video'] as String? ?? '',
  title: json['title'] as String? ?? '',
  dtitle: json['dtitle'] as String? ?? '',
  monthSales: json['monthSales'] as num? ?? 0,
  subdivisionRank: json['subdivisionRank'] as num? ?? 0,
  hzQuanOver: json['hzQuanOver'] as num? ?? 0,
  isSubdivision: json['isSubdivision'] as num? ?? 0,
  directCommissionType: json['directCommissionType'] as num? ?? 0,
  servicePercent: json['servicePercent'] as num? ?? 0,
  commissionType: json['commissionType'] as num? ?? 0,
  directCommission: json['directCommission'] as num? ?? 0,
  twoHoursSales: json['twoHoursSales'] as num? ?? 0,
  dsrPercent: json['dsrPercent'] as num? ?? 0,
  estimateAmount: json['estimateAmount'] as num? ?? 0,
  couponPrice: json['couponPrice'] as num? ?? 0,
  activityType: json['activityType'] as num? ?? 0,
  hotPush: json['hotPush'] as num? ?? 0,
  marketingMainPic: json['marketingMainPic'] as String? ?? '',
  couponEndTime: json['couponEndTime'] as String? ?? '',
  createTime: json['createTime'] as String? ?? '',
  subdivisionName: json['subdivisionName'] as String? ?? '',
  circleText: json['circleText'] as String? ?? '',
  specialText: json['specialText'] as List<dynamic>? ?? const [],
);

Map<String, dynamic> _$ProductToJson(_Product instance) => <String, dynamic>{
  'teamName': instance.teamName,
  'tbcid': instance.tbcid,
  'shipPercent': instance.shipPercent,
  'itemLink': instance.itemLink,
  'freeshipRemoteDistrict': instance.freeshipRemoteDistrict,
  'yunfeixian': instance.yunfeixian,
  'goldSellers': instance.goldSellers,
  'reimgs': instance.reimgs,
  'couponLink': instance.couponLink,
  'haitao': instance.haitao,
  'sellerId': instance.sellerId,
  'discounts': instance.discounts,
  'directCommissionLink': instance.directCommissionLink,
  'couponStartTime': instance.couponStartTime,
  'serviceScore': instance.serviceScore,
  'mainPic': instance.mainPic,
  'id': instance.id,
  'brand': instance.brand,
  'imgs': instance.imgs,
  'brandName': instance.brandName,
  'couponConditions': instance.couponConditions,
  'detailPics': instance.detailPics,
  'subcid': instance.subcid,
  'subdivisionId': instance.subdivisionId,
  'dsrScore': instance.dsrScore,
  'dailySales': instance.dailySales,
  'shopLogo': instance.shopLogo,
  'shopLevel': instance.shopLevel,
  'couponTotalNum': instance.couponTotalNum,
  'descScore': instance.descScore,
  'brandWenan': instance.brandWenan,
  'activityEndTime': instance.activityEndTime,
  'shipScore': instance.shipScore,
  'brandId': instance.brandId,
  'couponReceiveNum': instance.couponReceiveNum,
  'shopType': instance.shopType,
  'cid': instance.cid,
  'desc': instance.desc,
  'commissionRate': instance.commissionRate,
  'originalPrice': instance.originalPrice,
  'actualPrice': instance.actualPrice,
  'goodsId': instance.goodsId,
  'quanMLink': instance.quanMLink,
  'shopName': instance.shopName,
  'activityStartTime': instance.activityStartTime,
  'video': instance.video,
  'title': instance.title,
  'dtitle': instance.dtitle,
  'monthSales': instance.monthSales,
  'subdivisionRank': instance.subdivisionRank,
  'hzQuanOver': instance.hzQuanOver,
  'isSubdivision': instance.isSubdivision,
  'directCommissionType': instance.directCommissionType,
  'servicePercent': instance.servicePercent,
  'commissionType': instance.commissionType,
  'directCommission': instance.directCommission,
  'twoHoursSales': instance.twoHoursSales,
  'dsrPercent': instance.dsrPercent,
  'estimateAmount': instance.estimateAmount,
  'couponPrice': instance.couponPrice,
  'activityType': instance.activityType,
  'hotPush': instance.hotPush,
  'marketingMainPic': instance.marketingMainPic,
  'couponEndTime': instance.couponEndTime,
  'createTime': instance.createTime,
  'subdivisionName': instance.subdivisionName,
  'circleText': instance.circleText,
  'specialText': instance.specialText,
};
